/** Auto-generated by scripts/generate-icon.ts — do not edit directly. */
export const ICON_SVG =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">\n  <rect width="512" height="512" rx="115" ry="115" fill="#228be6"/>\n  <text\n    x="256"\n    y="318"\n    font-size="224"\n    font-family="ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace"\n    font-weight="700"\n    fill="white"\n    text-anchor="middle"\n    dominant-baseline="auto"\n    letter-spacing="-8"\n  >ts-ha</text>\n</svg>';
