#!/usr/bin/env bun
/**
 * Build script for the web status page frontend.
 *
 * Uses Bun.build to compile the React + Mantine app into a self-contained
 * JS bundle and a single CSS file, then writes them as TypeScript string
 * constants into the asset modules that html-shell.ts imports.
 *
 * Run automatically via:
 *   - prebuild          (bun run build)
 *   - build:status-page (bun run build:status-page)
 */

import { join } from "node:path";
import { existsSync } from "node:fs";

const ROOT = join(import.meta.dirname, "..");
const ENTRY = join(ROOT, "src/core/status-page/app/index.tsx");
const OUT_JS = join(ROOT, "src/core/status-page/assets/app-js.ts");
const OUT_CSS = join(ROOT, "src/core/status-page/assets/style-css.ts");

// Skip if the entry point doesn't exist yet (e.g. during initial bun install
// before the repo is fully set up, or in CI environments building only the
// server-side package).
if (!existsSync(ENTRY)) {
  console.log("[build-status-page] Entry point not found, skipping.");
  process.exit(0);
}

console.log("[build-status-page] Building React + Mantine frontend…");

const result = await Bun.build({
  entrypoints: [ENTRY],
  target: "browser",
  format: "esm",
  minify: true,
  // Override the repo-wide jsxImportSource (@opentui/react) so the browser
  // bundle uses standard React JSX, not OpenTUI intrinsics.
  jsx: {
    runtime: "automatic",
    importSource: "react",
  },
  // No outdir → in-memory artifacts only; we write them ourselves below.
});

if (!result.success) {
  console.error("[build-status-page] Build failed:");
  for (const log of result.logs) {
    console.error(" ", log);
  }
  process.exit(1);
}

let js = "";
let css = "";

for (const artifact of result.outputs) {
  const text = await artifact.text();
  if (artifact.path.endsWith(".css")) {
    css += text;
  } else {
    js += text;
  }
}

if (!js) {
  console.error("[build-status-page] No JS output produced.");
  process.exit(1);
}

// Escape </script> so the bundle is safe to inline inside an HTML <script> tag.
//
// The HTML parser closes a <script> block at the first </script> it encounters,
// regardless of whether it is inside a JS string literal. React's DOM internals
// contain the literal sequence `</script>` (used as an innerHTML shortcut), which
// causes the browser to terminate the script block mid-bundle — rendering the rest
// of the 600+ KB bundle as visible text on the page.
//
// The fix: replace every </script> with <\/script>. The backslash before `/` is a
// no-op in JavaScript string context (it evaluates to the same `/` character), so
// the runtime value is identical. The HTML parser, however, will not treat
// <\/script> as a closing tag and will leave the script block intact.
js = js.replaceAll("</script>", "<\\/script>");

// Write JS constant — biome noTemplateCurlyInString suppressed via biome.json override
await Bun.write(
  OUT_JS,
  `/** Auto-generated by scripts/build-status-page.ts — do not edit directly. */\nexport const JS = ${JSON.stringify(js)};\n`,
);

// Write CSS constant (may be empty if Mantine injects styles at runtime via style tags)
await Bun.write(
  OUT_CSS,
  `/** Auto-generated by scripts/build-status-page.ts — do not edit directly. */\nexport const CSS = ${JSON.stringify(css)};\n`,
);

const jsSizeKb = (js.length / 1024).toFixed(1);
const cssSizeKb = (css.length / 1024).toFixed(1);
console.log(`[build-status-page] Done. JS: ${jsSizeKb} KB, CSS: ${cssSizeKb} KB`);
