#!/usr/bin/env bun
/**
 * Generates the SVG app icon and writes it as a TypeScript string constant
 * into src/core/web-ui/assets/icon-svg.ts (git-ignored, like app-js.ts).
 *
 * The icon is a 512×512 SVG:
 *   - Mantine blue (#228be6) rounded square background (iOS icon radius)
 *   - White "ts" initials in bold monospace, vertically centred
 *
 * Run automatically as the first step of build:web-ui.
 */

import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const OUT = join(ROOT, "src/core/web-ui/assets/icon-svg.ts");

const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <rect width="512" height="512" rx="115" ry="115" fill="#228be6"/>
  <text
    x="256"
    y="318"
    font-size="224"
    font-family="ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace"
    font-weight="700"
    fill="white"
    text-anchor="middle"
    dominant-baseline="auto"
    letter-spacing="-8"
  >ts-ha</text>
</svg>`;

await Bun.write(
  OUT,
  `/** Auto-generated by scripts/generate-icon.ts — do not edit directly. */\nexport const ICON_SVG = ${JSON.stringify(svg)};\n`,
);

console.log("[generate-icon] Done. SVG icon written.");
