/**
 * Shared types and helpers for the web UI's build-time asset manifest.
 *
 * The manifest itself (`./manifest.ts`) is generated by
 * `scripts/build-web-ui.ts` and git-ignored. This module is checked in so
 * both the generator and the server-side consumers (asset routes, html
 * shell, budget test) share one definition.
 */

/**
 * One compiled asset (a JS or CSS bundle chunk).
 *
 * Bodies are stored base64-encoded so they can live inside a generated
 * TypeScript string constant regardless of whether the underlying bytes are
 * valid UTF-8 (the gzip body never is).
 */
export interface BuiltAsset {
  /** Content-hashed file name, e.g. "index-a1b2c3d4.js". Unique per build. */
  fileName: string;
  /** MIME type to serve, e.g. "application/javascript" or "text/css". */
  contentType: string;
  /** Hex digest of the raw (uncompressed) body, used to derive `fileName`. */
  hash: string;
  /** Raw, uncompressed body, base64-encoded. */
  rawBase64: string;
  /** Gzip-compressed body, base64-encoded. Always smaller than `rawBase64`. */
  gzipBase64: string;
  /**
   * Whether this asset is required for first paint. `false` for chunks only
   * reachable via a dynamic import, which are excluded from the first-paint
   * budget and not fetched until the feature that imports them is opened.
   */
  firstPaint: boolean;
}

/** Decodes a base64 string into raw bytes. */
export function base64ToBytes(base64: string): Uint8Array {
  return new Uint8Array(Buffer.from(base64, "base64"));
}

/** Encodes raw bytes into a base64 string. */
export function bytesToBase64(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64");
}

/**
 * Returns true when the given `Accept-Encoding` header value indicates the
 * client accepts gzip-encoded responses.
 *
 * A missing or absent header means no compression is accepted. An explicit
 * `gzip;q=0` disables gzip even if the token is present.
 */
export function clientAcceptsGzip(acceptEncodingHeader: string | undefined | null): boolean {
  if (!acceptEncodingHeader) return false;

  for (const rawToken of acceptEncodingHeader.split(",")) {
    const [name, ...params] = rawToken
      .trim()
      .toLowerCase()
      .split(";")
      .map((part) => part.trim());
    if (name !== "gzip") continue;

    const qParam = params.find((p) => p.startsWith("q="));
    if (qParam) {
      const q = Number.parseFloat(qParam.slice(2));
      if (!Number.isNaN(q) && q === 0) return false;
    }
    return true;
  }

  return false;
}

/**
 * Selects the best body to serve for an asset given whether the client
 * accepts gzip. Returns the raw body when it does not.
 */
export function selectAssetBody(
  asset: BuiltAsset,
  acceptsGzip: boolean,
): { body: Uint8Array; contentEncoding: "gzip" | null } {
  if (acceptsGzip) {
    return { body: base64ToBytes(asset.gzipBase64), contentEncoding: "gzip" };
  }
  return { body: base64ToBytes(asset.rawBase64), contentEncoding: null };
}

/**
 * Total transferred bytes (gzip body sizes) for every asset required for
 * first paint. Used by the build-time budget assertion (D24, D26).
 */
export function firstPaintTransferredBytes(assets: readonly BuiltAsset[]): number {
  let total = 0;
  for (const asset of assets) {
    if (!asset.firstPaint) continue;
    total += base64ToBytes(asset.gzipBase64).byteLength;
  }
  return total;
}
